replication_factor = 1

db_engine = "sqlite"

metadata_dir = "./tmp/garage/meta"
data_dir = [
  { path = "./tmp/garage/data", capacity = "100M" }
]

metadata_fsync = false
data_fsync = false

disable_scrub = true

compression_level = 3

rpc_bind_addr = "[::1]:3900"

# INSECURE.
allow_world_readable_secrets = true
rpc_secret = "b80658fbdc090d79897869398f30a7c6bccc042bdb38309f6e58742276927793"

[s3_api]
api_bind_addr = "[::1]:3901"
root_domain = "s3.spetsctf.local"
s3_region = "spetsctf-dev"

[s3_web]
bind_addr = "[::1]:3902"
root_domain = "s3web.spetsctf.local"
