name: Checks
on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  check-and-eval:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@2c9db80fb984ceb1bcaa77cdda3fdf8cfba92035 # v34
        with:
          nix_conf: |
            keep-env-derivations = true
            keep-outputs = true
      - name: Restore Nix Store
        uses: nix-community/cache-nix-action/restore@135667ec418502fa5a3598af6fb9eb733888ce6a # v6.1.3
        with:
          primary-key: nix-${{ runner.arch }}-${{ runner.os }}-${{ hashFiles('flake.lock', 'bun.lock') }}
      - name: Check Flake
        run: nix --extra-experimental-features 'nix-command flakes' flake check
      - name: Build SpetsCTF package
        run: nix --extra-experimental-features 'nix-command flakes' build .#spetsctf
      - name: Save Nix store
        uses: nix-community/cache-nix-action/save@135667ec418502fa5a3598af6fb9eb733888ce6a # v6.1.3
        if: always()
        id: cache
        with:
          primary-key: nix-${{ runner.arch }}-${{ runner.os }}-${{ hashFiles('flake.lock', 'bun.lock') }}
          # Purge cache after 31 days.
          purge: true
          purge-last-accessed: 2678400
